### ISSUE TITLE
support for symfony 3.0

### ISSUE THREAD

**Issue by MassiveHiggsField** [krichprollsch/process-builder-chain#2]
This package requires symfony/process 2.5, so it can't be installed with the newly released symfony 3.0

**Comment by krichprollsch** [comment]
Yeah good point thank you!
I just push a `bump-process` branch. Could you try it to check if all is ok for you before merge ?

**Comment by MassiveHiggsField** [comment]
Yep i'll check that and get back to you

**Comment by MassiveHiggsField** [comment]
Sry took some days but i'm not working on that project that often. I tested the bump branch and everything seems to be working fine. All tests are green and composer updates are working.

**Comment by krichprollsch** [comment]
No problem, thank you for your tests. I merge and I create a tag ^^
